version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: taskmanager-db
    restart: always
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432" # host:container (avoid clash with local Postgres on 5432)
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - task-net

  backend:
    build: ./backend # uses backend/Dockerfile
    container_name: taskmanager-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080" # backend on http://localhost:8080
    networks:
      - task-net

  frontend:
    build: ./frontend # uses frontend/Dockerfile (Vite â†’ Nginx)
    container_name: taskmanager-frontend
    depends_on:
      - backend
    ports:
      - "3000:80" # frontend on http://localhost:3000
    networks:
      - task-net

networks:
  task-net:
    driver: bridge

volumes:
  postgres-data:
